import esbuild from 'esbuild';
import { copyFileSync, existsSync } from 'node:fs';
import process from 'process';
import { builtinModules } from 'node:module';

const DIST_DIR = 'dist';
const OUT_JS = `${DIST_DIR}/main.js`;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

function copyVaultAssetsPlugin() {
	return {
		name: 'copy-vault-assets',
		setup(build) {
			build.onEnd(() => {
				if (existsSync('styles.css')) {
					copyFileSync('styles.css', `${DIST_DIR}/styles.css`);
				}
			});
		}
	};
}

const context = await esbuild.context({
	banner: {
		js: banner
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: OUT_JS,
	minify: prod,
	plugins: [copyVaultAssetsPlugin()]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
